axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.5
scale_linear_turbo: 1.2

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 0.6

enable_button: 2  # Left trigger button
enable_turbo_button: 5  # Right trigger button